spring:
  profiles:
    active: datasource,logging
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false

server:
  port: 9090

logging:
  level:
    io.mpk3s: DEBUG

multipass:
  command: multipass
  kubeconfig-dir: ${user.home}/.kube

encryption:
  key: ${ENCRYPTION_KEY:0000000000000000000000000000000000000000000000000000000000000000}
